//These constraints are set to apply for Basys-3 FPGA board.

set_property PACKAGE_PIN W17 [get_ports {in[3]}]
set_property PACKAGE_PIN W16 [get_ports {in[2]}]
set_property PACKAGE_PIN V16 [get_ports {in[1]}]
set_property PACKAGE_PIN V17 [get_ports {in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp[6]}]
set_property PACKAGE_PIN W7 [get_ports {disp[6]}]
set_property PACKAGE_PIN W6 [get_ports {disp[5]}]
set_property PACKAGE_PIN U8 [get_ports {disp[4]}]
set_property PACKAGE_PIN V8 [get_ports {disp[3]}]
set_property PACKAGE_PIN U5 [get_ports {disp[2]}]
set_property PACKAGE_PIN V5 [get_ports {disp[1]}]
set_property PACKAGE_PIN U7 [get_ports {disp[0]}]
