set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN U18 [get_ports reset]

create_clock -period 10.00 [get_ports clk_100MHz]
set_property -dict {PACKAGE_PIN W5 IOSTANDARD LVCMOS33} [get_ports clk_100MHz]

#7 displayerment display
set_property PACKAGE_PIN W7 [get_ports {displayer[6]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {displayer[6]}]
set_property PACKAGE_PIN W6 [get_ports {displayer[5]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {displayer[5]}]
set_property PACKAGE_PIN U8 [get_ports {displayer[4]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {displayer[4]}]
set_property PACKAGE_PIN V8 [get_ports {displayer[3]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {displayer[3]}]
set_property PACKAGE_PIN U5 [get_ports {displayer[2]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {displayer[2]}]
set_property PACKAGE_PIN V5 [get_ports {displayer[1]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {displayer[1]}]
set_property PACKAGE_PIN U7 [get_ports {displayer[0]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {displayer[0]}]


set_property PACKAGE_PIN U2 [get_ports {digit_selector[0]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {digit_selector[0]}]
set_property PACKAGE_PIN U4 [get_ports {digit_selector[1]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {digit_selector[1]}]
set_property PACKAGE_PIN V4 [get_ports {digit_selector[2]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {digit_selector[2]}]
set_property PACKAGE_PIN W4 [get_ports {digit_selector[3]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {digit_selector[3]}]
